### ISSUE TITLE
세미나 참여 기준과 관련하여 질문 드립니다.

### ISSUE THREAD

**Issue by fluentmin** [wafflestudio/seminar-2022#195]
안녕하세요. 와플스튜디오 20.5기 루키 유창민이라고 합니다. 세미나 참여 기준과 관련하여 질문할 사항이 두 가지 있어 질문 드립니다.

1. 세미나에 비대면으로 참여하는 경우에도 줌을 통해 해당 세미나 시간 동안 접속한다면 출석으로 인정받을 수 있나요?
2. 만약 개인사정으로 인해 실시간 세미나에 참석하기 어려운 경우, 출석 인정을 위한 대체 방법이 있나요?

감사합니다!

**Comment by fluentmin** [comment]
Issue 생성 후 Label과 Milestone을 추가하려고 하였으나, 해당 기능을 사용할 수 없어 이대로 올립니다..!
오티 자료 보면 Label과 Milestone 옆에 설정 아이콘(톱니바퀴)이 있는데, 현재 제 계정에서는 보이지가 않네요.

**Comment by hanan-nana** [comment]
안녕하세요! 와플스튜디오 운영팀 김지호입니다.

1. 넵, 비대면 출석도 출석으로 인정됩니다.
2. 운영팀에서는 따로 예외를 두고 있지 않으며, 출석 반영 또한 세미나장님의 재량에 따릅니다. 다만, 부득이한 경우에 세미나장님이나 운영팀에게 미리 알려주시면 논의 후 결정드릴 수 있습니다.
감사합니다!
