### ISSUE TITLE
Android Codelab 링크 관련 질문드립니다.

### ISSUE THREAD

**Issue by RyuGaeun4201** [wafflestudio/seminar-2022#202]
제공해주신 해당 Android Codelab 링크 https://developer.android.com/courses/kotlin-android-fundamentals/overview 로 접속하니 "Caution: This course is no longer maintained. Please use _Android Basics in Kotlin_ or _Android Basics with Compose_ instead." 라는 문구가 나타납니다. 혹시 명시된 대로 _Android Basics in Kotlin_ 에 연결된 https://developer.android.com/courses/android-basics-kotlin/course 링크의 course로 과제 진행해도 문제 없을까요?

감사합니다 :)

**Comment by gyusang** [comment]
@sanggggg

**Comment by sanggggg** [comment]
헉 네네, 한국어로 볼 때 deprecation 이 안 보여서 모르고 있었네요

말씀해주신 링크의 1, 2로 진행해도 괜찮을 것 같습니다.

Optional 과제인 만큼 원하는 방향으로 진행해주셔도 괜찮습니다 둘 다 어느정도 내용이 비슷하네요

제보 해주셔서 감사합니다 🙇
